
server:
  port: 8080
  
spring:
  application:
    name: ERS
  datasource:    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres 
  jpa:
    hibernate:
      ddl-auto: update